### ISSUE TITLE
How do you use a GitLab.com repo?

### ISSUE THREAD

**Issue by waynebloss** [digitalocean/sample-html#2]
Your documentation says that you support private GitLab.com repos. How do you set that in app.yaml?

**Comment by jonfriesen** [comment]
Hi @waynebloss 

When creating a DigitalOcean App Platform app, you can authenticate with your GitLab account. This will then allow you to view your private repositories.

[Here's a link to create an app](https://cloud.digitalocean.com/apps/new)

Also this is not a good place for general App Platform support, here are some places:

- Our community board for general questions [[Link]](https://www.digitalocean.com/community/questions)
- Submit a support ticket for App Platform related issues [[Link]](https://do.co/2RvJI2Y)
